### PR TITLE
Support Curtain 3

### PR DESCRIPTION
**Pull request by the-ress**
Adds Curtain 3 support. Fixes home-assistant/core#99105.

It has a new model character (`{`/`[`), but otherwise seems to work with the existing code. It also includes battery level in manufacturer data. I'm not sure if that's specific to Curtain 3, or firmware 0.7.

In passive mode, Curtain 3 gets detected as a contact sensor because it has the same manufacturer data length. I couldn't figure out how to distinguish between them (and I don't have any contact sensors to investigate further).

<details>
<summary>Here are some manufacturer data values I recorded during testing.</summary>

```
byte 0 counter?
byte 1 ?
byte 2 position
byte 3 light level, device chain
byte 4 ?
byte 5 00
byte 6 battery

dc-xx-xx-xx-xx-xx-e5-03-00-11-03-00-56
ed-xx-xx-xx-xx-xx-a6-03-00-11-04-00-4b
d2-xx-xx-xx-xx-xx-cb-03-63-11-04-00-57
ed-xx-xx-xx-xx-xx-c4-03-b0-11-04-00-4b opening
ed-xx-xx-xx-xx-xx-c5-03-ad-11-04-00-4b opening
ed-xx-xx-xx-xx-xx-c6-03-aa-11-04-00-4b opening
ed-xx-xx-xx-xx-xx-c7-03-a8-11-04-00-4b opening
ed-xx-xx-xx-xx-xx-ce-03-19-11-04-00-4b stopped
ed-xx-xx-xx-xx-xx-da-03-00-11-04-00-4b stopped at open
ed-xx-xx-xx-xx-xx-e5-03-00-11-04-00-4b stopped at open
ed-xx-xx-xx-xx-xx-0f-03-64-11-04-00-4b stopped at closed
ed-xx-xx-xx-xx-xx-10-07-e4-11-04-00-4a opening
ed-xx-xx-xx-xx-xx-11-07-e3-11-04-00-4a opening
ed-xx-xx-xx-xx-xx-12-07-e1-11-04-00-4a opening
ed-xx-xx-xx-xx-xx-13-07-de-11-04-00-4a opening
ed-xx-xx-xx-xx-xx-19-07-ce-11-04-00-4a opening then stopped
ed-xx-xx-xx-xx-xx-1a-07-cb-11-04-00-4a opening then stopped
ed-xx-xx-xx-xx-xx-1d-07-48-11-05-00-4a opening then stopped
ed-xx-xx-xx-xx-xx-20-07-cd-11-05-00-4a closing then stopped
ed-xx-xx-xx-xx-xx-21-07-d0-11-05-00-4a closing then stopped
ed-xx-xx-xx-xx-xx-23-07-51-11-05-00-4a stopped
ed-xx-xx-xx-xx-xx-2c-07-64-11-04-00-4a stopped at closed
ed-xx-xx-xx-xx-xx-32-07-d8-11-04-00-4a opening
ed-xx-xx-xx-xx-xx-35-07-d0-11-04-00-4a opening
ed-xx-xx-xx-xx-xx-55-07-00-11-04-00-4a stopped at open
ed-xx-xx-xx-xx-xx-55-07-00-11-04-00-4a stopped at open again
```
</details>

### CODE REVIEW

**Comment by bdraco** [comment]
We can remove the passive detection of contact sensors by deleting the line with the 13 length.

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Thanks @the-ress

**Comment by bdraco** [comment]
https://github.com/Danielhiversen/pySwitchbot/releases/tag/0.40.0

**Comment by the-ress** [comment]
> We can remove the passive detection of contact sensors by deleting the line with the 13 length.

Won’t that break pairing for people using contact sensors with passive bluetooth?

**Comment by bdraco** [comment]
> > We can remove the passive detection of contact sensors by deleting the line with the 13 length.
> 
> Won’t that break pairing for people using contact sensors with passive bluetooth?

No, because HA stores the sensor type in the config entry so it already knows what it is, it just means new ones can't be detected with passive only.

Its pretty clear thats unsupported anyways https://github.com/home-assistant/core/blob/8a98a0e830e9381d9959d8b7b7e732b27f6be5ff/homeassistant/components/switchbot/strings.json#L47

**Comment by the-ress** [comment]
That makes sense, thanks.

**Pull request merged**
