### PR TITLE
Fix contact_open timeout

### PR DESCRIPTION
**Pull request by dcousens**
(see https://github.com/OpenWonderLabs/SwitchBotAPI-BLE/issues/15#issuecomment-1368175346)

As is, the contact only "stays" open for 60 seconds, which is wrong.

### CODE REVIEW

**Comment by bdraco** [comment]
@dcousens I tweaked it a bit and fixed the test.  Does this still work for you as expected?

**Comment by dcousens** [comment]
@bdraco I don't use this library, unfortunately. https://github.com/Danielhiversen/pySwitchbot/pull/184/commits/7c62122b93109df70ebefa40dc382db59d94b0cc LGTM though

**Comment by bdraco** [comment]
Looks like I need to dig this sensor back out of storage for testing 🤣

**Comment by bdraco** [comment]
confirmed the fix when active scans are disabled 👍

**Pull request merged**
