### PR TITLE
Additional functionality for Bot and Curtain, reliability improvements.

### PR DESCRIPTION
**Pull request by RenierM26**
Bug Fixes:
- The _connect function now waits while another bluepy operation is in progress!

Common:
- Changed ```get_basic_info``` function to allow reuse for any device notifications via key.
- Combine ```_get_basic_info``` and ```send_command``` methods.
  - Check actual SB response to command issued. (Success/Fail, some also return the SB state. Will expand on this in future pull requests.)
  - Inform if password required or password incorrect.
- Allow passive scanning if the users' environment requires. (Could be used for background monitoring of state changes)
- Optimization of BTLE Scanning functions.
- Discover returns ADV data for unsupported switchbots. (To facilitate adding support for other SB devices) 

Bot:
- Add functions to set Bot mode. 
  - Set Bot to switch/toggle or inverse switch mode.
  - Set strength of bot arm.
  - Set bot long press duration in seconds.
- Add Execute Arm up/down function to Bot.

Curtain:
- Add get extended settings for curtains.
- btle scan adv data also returns additional data:
  - Inmotion (when busy moving) and deviceChain (if grouped curtain bots). The example is for the 1s one in the chain)
 
```
  	"777777777777": {
		"mac_address": "77:77:77:77:77:77",
		"isEncrypted": false,
		"model": "c",
		"data": {
			"calibration": true,
			"battery": 40,
			"inMotion": false,
			"position": 100,
			"lightLevel": 2,
			"deviceChain": 1,
			"rssi": -71
		},
		"modelName": "WoCurtain"
```

# Added device info methods:

```curtain = switchbot.SwitchbotCurtain(mac="d6:2f:ff:ff:ff:ff")```

```curtain.get_extended_info_summary()```

Successfully retrieved data from device d6:2f:ff:ff:ff:ff
{'device0': {'openDirectionDefault': False, 'touchToOpen': True, 'light': True, 'openDirection': 'right_to_left'}, 'device1': {'openDirectionDefault': False, 'touchToOpen': True, 'light': True, 'openDirection': 'left_to_right'}}

```curtain.get_extended_info_adv()```

Successfully retrieved data from device d6:2f:ff:ff:ff:ff
{'device0': {'battery': 82, 'firmware': 3.1, 'stateOfCharge': 'not_charging'}, 'device1': {'battery': 83, 'firmware': 3.1, 'stateOfCharge': 'not_charging'}}

### CODE REVIEW

**Comment by RenierM26** [comment]
Just discovered that all commands sent also respond with a status on the notification handle. 

This way we can also check if the command fails due to incorrect password (currently it just succeeds with no error or notification)

Busy testing this.

**Comment by RenierM26** [comment]
Found a way to check if helper is running and the state of the helper. Busy testing as this could prevent connection errors.

**Comment by RenierM26** [comment]
Hi @Danielhiversen,

I'm really sorry for the large pull request. This one has a lot of reliability fixes and optimizations! 

Think I also made some of the code easier to read/interpret.

**Comment by RenierM26** [comment]
And who said BT can't be reliable. ;-)

**Review by Danielhiversen — APPROVED** [review]
Nice.
Do not have much time to review now, but it looks good to me

**Pull request merged**
