### PR TITLE
Add basic support for the Meter Pro

### PR DESCRIPTION
**Pull request by bdraco**
Only supports temp and humidity at this point

### CODE REVIEW

**Comment by talormanda** [comment]
Does this support the meter pro and the CO2 version? The regular meter pro is model: w4900000 and the CO2 model is w4900010.

**Comment by bdraco** [comment]
No co2 support.  I don't have one

**Comment by talormanda** [comment]
> No co2 support. I don't have one

is there anything i can do to contribute to help get you what you need to add this?

**Comment by bdraco** [comment]
Probably not. It takes orders of magnitude more time to figure out a device when it's not in hand

**Comment by talormanda** [comment]
I'm certainly willing to try if you ever change your mind.

**Comment by bdraco** [comment]
@talormanda post the advertisement data in https://github.com/Danielhiversen/pySwitchbot/issues/251. Maybe you will get lucky and its easy to decode

**Comment by bdraco** [comment]
Previous examples https://github.com/Danielhiversen/pySwitchbot/issues/136

Can be extracted from Bluetooth Diagnostics or ESPHome Diagnostics or Shelly Diagnostics depending on which Bluetooth adapter you have.

Match the mac address to the one in the switchbot app

**Comment by talormanda** [comment]
> Previous examples #136
> 
> Can be extracted from Bluetooth Diagnostics or ESPHome Diagnostics or Shelly Diagnostics depending on which Bluetooth adapter you have.
> 
> Match the mac address to the one in the switchbot app

I actually have all 3 of those things operating. I will inspect it right now and see.

**Comment by talormanda** [comment]
Posted data in https://github.com/Danielhiversen/pySwitchbot/issues/251

**Pull request merged**
