### PR TITLE
Add verify_encryption_key for lock

### PR DESCRIPTION
**Pull request by dsypniewski**
Adding verify_encryption_key to use for HA config flow

### CODE REVIEW

**Review by bdraco — APPROVED** [review]

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
0.33.0

**Comment by donavanbecker** [comment]
@dsypniewski Could you update the SwitchBot-BLE repo with your findings?

**Comment by dsypniewski** [comment]
@donavanbecker I'll need some time to finish things up and clean-up my notes, but after I'm done I can open a PR there.

**Comment by donavanbecker** [comment]
Thanks @dsypniewski!

**Pull request merged**
